### ISSUE TITLE
iOS Implementation

### ISSUE THREAD

**Issue by SandyAra** [dreamsoftin/facebook_audience_network#19]

**Comment by BPHvZ** [comment]
Is iOS implementation possible using UiKitView? https://api.flutter.dev/flutter/widgets/UiKitView-class.html

**Comment by SachinGanesh** [comment]
Possible. We don't have immediate plans of implementing it yet. We are open to PR's

**Comment by malikdoksoz** [comment]
We are waiting ios version

**Comment by nextkhit** [comment]
Does it have others solutions for IOS? any suggestion?

**Comment by eleomilagrosa** [comment]
Any Update?

**Comment by casualcoder404** [comment]
> Possible. We don't have immediate plans of implementing it yet. We are open to PR's

Please work on iOS implementation.

**Comment by SachinGanesh** [comment]
Hi all, iOS support is now available. Please check "ios" branch. If everything works fine we will release it through pub.dev

You can use the below dependecy to test the integration
```yaml
facebook_audience_network: 
    git: 
      url: git@github.com:dreamsoftin/facebook_audience_network.git
      ref: ios
```
