### ISSUE TITLE
Brilliant BUT we REALLY need iOS compatibility

### ISSUE THREAD

**Issue by johnmollaghan** [dreamsoftin/facebook_audience_network#32]
Do you have any timeline on when this will also work on iOS?

**Comment by SachinGanesh** [comment]
Hi, iOS support is now available. Please check "ios" branch. If everything works fine we will release it through pub.dev

You can use the below dependecy to test the integration
```yaml
facebook_audience_network: 
    git: 
      url: git@github.com:dreamsoftin/facebook_audience_network.git
      ref: ios
```
