### ISSUE TITLE
please add ios platform

### ISSUE THREAD

**Issue by mrthuan** [dreamsoftin/facebook_audience_network#33]
please add ios platform

**Comment by kellvembarbosa** [comment]
UP, please add ios

**Comment by WieFel** [comment]
+1

**Comment by SachinGanesh** [comment]
Hi all, iOS support is now available. Please check "ios" branch. If everything works fine we will release it through pub.dev

You can use the below dependecy to test the integration
```yaml
facebook_audience_network: 
    git: 
      url: git@github.com:dreamsoftin/facebook_audience_network.git
      ref: ios
```
