### ISSUE TITLE
Native Banner Ad blank space if Ad not loaded

### ISSUE THREAD

**Issue by Omi231** [dreamsoftin/facebook_audience_network#34]
The fill rate inside my app is less than 30% these days thats why most of the users see a blank space instead of ad. Is there any way i can show a custom ad to promote my other app or atleast hide that blank space?

This is the sole reason I have removed native banner ads from the app for now because the empty space make the UI look ugly :(

**Comment by SachinGanesh** [comment]
Hi, Thank you for the feedback. We have added a feature to collapse the empty ad space and expand it only if the ad is loaded. We will be pushing the update in a day to two.

**Comment by Omi231** [comment]
@SachinGanesh Thank you so much. Waiting for the update...

**Comment by SachinGanesh** [comment]
Hi. This feature is now available through ios branch.  If everything works fine we will release it through pub.dev

You can use the below dependecy to test the integration
```yaml
facebook_audience_network: 
    git: 
      url: git@github.com:dreamsoftin/facebook_audience_network.git
      ref: ios
```
