### ISSUE TITLE
RewardedVideoAd is not loading in Android

### ISSUE THREAD

**Issue by FernandoUFS** [dreamsoftin/facebook_audience_network#85]
Hi, I am trying load rewarded video ads in Android, but simply nothing happens, no logs are shown at console.
I have already implemented successfully NativeAds.
 
This is my code, I tried execute it in `initState()` and also at a button click.

```
void loadAd(){
    print('Try load ad rewarded: ' + videoId;
    FacebookRewardedVideoAd.loadRewardedVideoAd(
      placementId: videoId,
      listener: (result, value) {
        print('Rewarded video: ' + result.toString() + ' => ' + value);
      },
    );
  }
```

**The console:**
```
...
I/flutter (30596): Try load ad rewarded: CCCCCCCCCCCCC_XXXXXXXXXXXXXX
(nothing more)
```

I already checked the ad id on facebook, it is all right.

**Flutter Doctor:**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (3 available)

• No issues found!
```

**My pubspec**
```
environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sign_in_with_apple: ^2.5.2
  admob_flutter: ^1.0.1
  flutter_native_admob: ^2.1.0+3
  archive: ^2.0.11
  appsflyer_sdk: ^6.0.5
  barcode_scan: ^1.0.0
  cached_network_image: ^2.0.0
  charts_flutter: ^0.8.1
  circular_countdown_timer: ^0.0.7
  configurable_expansion_tile: ^1.0.0
  country_pickers: ^1.3.0
  cupertino_icons: ^0.1.3
  data_tables: ^1.0.3
  date_range_picker: ^1.0.5
  flare_flutter: ^1.0.2
  fl_chart: ^0.9.4
  flutter_calendar_carousel: ^1.4.12
  flutter_cupertino_localizations: ^1.0.1
  flutter_slidable: ^0.5.3
  font_awesome_flutter: ^8.5.0
  json_annotation: ^3.0.1
  image_picker: ^0.6.7+14
  pretty_qr_code: ^1.0.1
  share: ^0.6.3+6
  sqflite: ^1.3.2+1
  url_launcher: ^5.7.10
  webview_flutter: ^1.0.7
  google_sign_in: ^4.5.1
  flutter_svg: ^0.18.0
  sliding_up_panel: ^1.0.2
  flutter_keyboard_visibility: ^3.2.1
  flutter_typeahead: ^1.8.7
  firebase_messaging: ^7.0.3
  just_audio: ^0.4.4
  uni_links: ^0.4.0
  backdrop: 0.3.2
  path_provider: ^1.6.24
  in_app_purchase: ^0.3.4+16
  firebase_analytics: ^6.2.0
  facebook_audience_network: ^0.8.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  json_serializable: ^3.2.0
  build_runner: ^1.7.4 #flutter pub run build_runner build --delete-conflicting-outputs
```
